import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import Footer from '../components/Footer'

const DOMAINS = [
  { id: 'dsa',         label: 'DSA',             icon: 'account_tree',            color: '#2f8e47' },
  { id: 'webdev',      label: 'Web Dev',          icon: 'web',                     color: '#3b82f6' },
  { id: 'aiml',        label: 'AI / ML',          icon: 'smart_toy',               color: '#f97316' },
  { id: 'datascience', label: 'Data Science',     icon: 'bar_chart',               color: '#8b5cf6' },
  { id: 'cybersec',    label: 'Cyber Security',   icon: 'security',                color: '#ef4444' },
  { id: 'blockchain',  label: 'Blockchain',       icon: 'currency_bitcoin',        color: '#eab308' },
  { id: 'cloud',       label: 'Cloud Computing',  icon: 'cloud',                   color: '#06b6d4' },
  { id: 'robotics',    label: 'Robotics',         icon: 'precision_manufacturing', color: '#ec4899' },
  { id: 'devops',      label: 'DevOps',           icon: 'settings_suggest',        color: '#14b8a6' },
  { id: 'mobile',      label: 'Mobile Dev',       icon: 'phone_android',           color: '#a855f7' },
]


const ROADMAPS = {
  dsa: [
    { id: 1, title: 'Programming Basics', icon: 'code', desc: 'Pick a language (C++/Java/Python). Learn variables, loops, functions, recursion, and time/space complexity basics.' },
    { id: 2, title: 'Arrays & Strings', icon: 'view_array', desc: 'Sliding window, two pointers, prefix sums, sorting, searching. Foundation for 40% of interview problems.' },
    { id: 3, title: 'Linked Lists', icon: 'linear_scale', desc: 'Singly & doubly linked lists, reversal, cycle detection (Floyd\'s), merge sorted lists, LRU cache.' },
    { id: 4, title: 'Stacks & Queues', icon: 'layers', desc: 'Monotonic stack, next greater element, BFS with queues, deque tricks, and expression evaluation.' },
    { id: 5, title: 'Trees & BST', icon: 'account_tree', desc: 'Binary trees, DFS/BFS traversals, BST operations, LCA, diameter, height, and segment trees.' },
    { id: 6, title: 'Heaps & Hashing', icon: 'filter_list', desc: 'Min/max heaps, priority queues, top-K problems, hash maps, hash sets, and collision handling.' },
    { id: 7, title: 'Graphs', icon: 'hub', desc: 'BFS, DFS, Dijkstra, Bellman-Ford, Floyd-Warshall, topological sort, union-find, and MST (Kruskal/Prim).' },
    { id: 8, title: 'Dynamic Programming', icon: 'psychology', desc: 'Memoization vs tabulation, knapsack, LCS, LIS, matrix DP, bitmask DP, and interval DP.' },
    { id: 9, title: 'Greedy & Backtracking', icon: 'shuffle', desc: 'Activity selection, Huffman coding, N-Queens, Sudoku solver, permutations, and subset generation.' },
    { id: 10, title: 'Advanced Topics', icon: 'star', desc: 'Tries, segment trees with lazy propagation, Fenwick trees, string algorithms (KMP, Z-function), and competitive tricks.' },
  ],
  webdev: [
    { id: 1, title: 'HTML & CSS Fundamentals', icon: 'html', desc: 'Semantic HTML5, CSS box model, flexbox, grid, responsive design, and accessibility basics.' },
    { id: 2, title: 'JavaScript Core', icon: 'javascript', desc: 'ES6+, closures, prototypes, async/await, promises, event loop, DOM manipulation, and fetch API.' },
    { id: 3, title: 'Version Control & Git', icon: 'merge', desc: 'Git workflow, branching strategies, pull requests, rebasing, and GitHub collaboration.' },
    { id: 4, title: 'React.js', icon: 'widgets', desc: 'Components, hooks (useState, useEffect, useContext), React Router, state management, and performance optimization.' },
    { id: 5, title: 'CSS Frameworks', icon: 'palette', desc: 'Tailwind CSS utility-first approach, component libraries (shadcn, Radix), and design systems.' },
    { id: 6, title: 'Node.js & Express', icon: 'dns', desc: 'REST API design, middleware, authentication (JWT/OAuth), file uploads, and error handling.' },
    { id: 7, title: 'Databases', icon: 'storage', desc: 'SQL (PostgreSQL/MySQL) vs NoSQL (MongoDB). Schema design, indexing, transactions, and ORMs.' },
    { id: 8, title: 'Authentication & Security', icon: 'lock', desc: 'JWT, OAuth2, session management, HTTPS, CORS, XSS/CSRF prevention, and rate limiting.' },
    { id: 9, title: 'Deployment & DevOps', icon: 'cloud_upload', desc: 'Docker basics, CI/CD pipelines, Vercel/Netlify, AWS/GCP basics, environment management.' },
    { id: 10, title: 'System Design', icon: 'architecture', desc: 'Load balancing, caching (Redis), CDN, microservices, message queues, and scalability patterns.' },
  ],
  aiml: [
    { id: 1, title: 'Python for ML', icon: 'code', desc: 'NumPy, Pandas, Matplotlib, Seaborn — the data science stack. Vectorized operations and data wrangling.' },
    { id: 2, title: 'Math Foundations', icon: 'calculate', desc: 'Linear algebra (matrices, eigenvalues), calculus (gradients, chain rule), probability, and statistics.' },
    { id: 3, title: 'Data Preprocessing', icon: 'tune', desc: 'Handling missing values, feature scaling, encoding, train/test splits, and cross-validation.' },
    { id: 4, title: 'Classical ML', icon: 'scatter_plot', desc: 'Linear/logistic regression, decision trees, random forests, SVM, KNN, and ensemble methods.' },
    { id: 5, title: 'Model Evaluation', icon: 'assessment', desc: 'Accuracy, precision, recall, F1, ROC-AUC, confusion matrix, bias-variance tradeoff, and overfitting.' },
    { id: 6, title: 'Deep Learning Basics', icon: 'hub', desc: 'Neural networks, backpropagation, activation functions, optimizers (Adam, SGD), and regularization.' },
    { id: 7, title: 'CNNs & Computer Vision', icon: 'image', desc: 'Convolutional layers, pooling, ResNet, VGG, transfer learning, object detection (YOLO), and segmentation.' },
    { id: 8, title: 'NLP & Transformers', icon: 'chat', desc: 'Tokenization, embeddings, RNNs, LSTMs, attention mechanism, BERT, GPT, and fine-tuning LLMs.' },
    { id: 9, title: 'MLOps', icon: 'settings_suggest', desc: 'Model versioning (MLflow), deployment (FastAPI, Docker), monitoring, A/B testing, and data pipelines.' },
    { id: 10, title: 'Generative AI', icon: 'auto_awesome', desc: 'GANs, VAEs, diffusion models, prompt engineering, RAG systems, and LangChain applications.' },
  ],
  datascience: [
    { id: 1, title: 'Python & R Basics', icon: 'code', desc: 'Python (pandas, numpy) and R for statistical computing. Jupyter notebooks and reproducible research.' },
    { id: 2, title: 'Statistics & Probability', icon: 'functions', desc: 'Descriptive stats, distributions, hypothesis testing, p-values, confidence intervals, and Bayesian thinking.' },
    { id: 3, title: 'Data Wrangling', icon: 'cleaning_services', desc: 'ETL pipelines, handling messy data, merging datasets, regex, and data quality checks.' },
    { id: 4, title: 'Exploratory Data Analysis', icon: 'search', desc: 'Univariate/bivariate analysis, correlation, outlier detection, and storytelling with data.' },
    { id: 5, title: 'Data Visualization', icon: 'bar_chart', desc: 'Matplotlib, Seaborn, Plotly, Tableau, and Power BI. Principles of effective visual communication.' },
    { id: 6, title: 'SQL & Databases', icon: 'storage', desc: 'Advanced SQL (window functions, CTEs), query optimization, and working with large datasets.' },
    { id: 7, title: 'Machine Learning', icon: 'smart_toy', desc: 'Supervised/unsupervised learning, feature engineering, model selection, and hyperparameter tuning.' },
    { id: 8, title: 'Big Data Tools', icon: 'cloud', desc: 'Spark, Hadoop, Hive, Kafka, and distributed computing concepts for petabyte-scale data.' },
    { id: 9, title: 'Business Intelligence', icon: 'insights', desc: 'KPI design, dashboards, A/B testing, cohort analysis, and translating data into business decisions.' },
    { id: 10, title: 'Capstone Projects', icon: 'star', desc: 'End-to-end projects: data collection → cleaning → analysis → modeling → presentation to stakeholders.' },
  ],
  cybersec: [
    { id: 1, title: 'Networking Fundamentals', icon: 'lan', desc: 'OSI model, TCP/IP, DNS, HTTP/S, firewalls, VPNs, and packet analysis with Wireshark.' },
    { id: 2, title: 'Linux & Command Line', icon: 'terminal', desc: 'Linux file system, permissions, bash scripting, process management, and system hardening.' },
    { id: 3, title: 'Cryptography', icon: 'key', desc: 'Symmetric/asymmetric encryption, hashing, PKI, TLS/SSL, digital signatures, and common attacks.' },
    { id: 4, title: 'Web Application Security', icon: 'security', desc: 'OWASP Top 10: SQLi, XSS, CSRF, IDOR, SSRF, broken auth, and security misconfigurations.' },
    { id: 5, title: 'Ethical Hacking & Recon', icon: 'manage_search', desc: 'OSINT, Nmap, Shodan, passive/active reconnaissance, and attack surface mapping.' },
    { id: 6, title: 'Exploitation Techniques', icon: 'bug_report', desc: 'Metasploit, buffer overflows, privilege escalation, reverse shells, and post-exploitation.' },
    { id: 7, title: 'Digital Forensics', icon: 'fingerprint', desc: 'Disk imaging, memory forensics, log analysis, incident response, and chain of custody.' },
    { id: 8, title: 'Malware Analysis', icon: 'coronavirus', desc: 'Static/dynamic analysis, reverse engineering (Ghidra, IDA), sandbox environments, and IOC extraction.' },
    { id: 9, title: 'Cloud Security', icon: 'cloud_done', desc: 'IAM misconfigurations, S3 bucket security, container security, and cloud-native attack vectors.' },
    { id: 10, title: 'CTF & Certifications', icon: 'workspace_premium', desc: 'Practice on HackTheBox, TryHackMe. Certifications: CEH, OSCP, CompTIA Security+, CISSP.' },
  ],
  blockchain: [
    { id: 1, title: 'Blockchain Fundamentals', icon: 'link', desc: 'Distributed ledgers, consensus mechanisms (PoW, PoS), immutability, and the Byzantine fault tolerance problem.' },
    { id: 2, title: 'Cryptography Basics', icon: 'key', desc: 'Hash functions (SHA-256), public/private keys, digital signatures, and Merkle trees.' },
    { id: 3, title: 'Bitcoin & Ethereum', icon: 'currency_bitcoin', desc: 'UTXO model, Bitcoin scripting, Ethereum accounts, gas, EVM, and the transition to PoS.' },
    { id: 4, title: 'Solidity Programming', icon: 'code', desc: 'Smart contract syntax, data types, mappings, events, modifiers, inheritance, and security patterns.' },
    { id: 5, title: 'Smart Contract Development', icon: 'contract', desc: 'Hardhat/Foundry setup, testing with Mocha/Chai, deployment scripts, and contract verification.' },
    { id: 6, title: 'DeFi Protocols', icon: 'account_balance', desc: 'AMMs (Uniswap), lending (Aave, Compound), yield farming, liquidity pools, and flash loans.' },
    { id: 7, title: 'NFTs & Token Standards', icon: 'token', desc: 'ERC-20, ERC-721, ERC-1155 standards, metadata, IPFS storage, and NFT marketplace mechanics.' },
    { id: 8, title: 'Web3 Frontend', icon: 'web', desc: 'ethers.js / wagmi, wallet connection (MetaMask, WalletConnect), React + Web3 dApp architecture.' },
    { id: 9, title: 'Smart Contract Security', icon: 'security', desc: 'Reentrancy, integer overflow, access control bugs, oracle manipulation, and audit tools (Slither, MythX).' },
    { id: 10, title: 'Layer 2 & Scaling', icon: 'speed', desc: 'Rollups (Optimism, Arbitrum, zkSync), state channels, sidechains, and cross-chain bridges.' },
  ],
  cloud: [
    { id: 1, title: 'Cloud Concepts', icon: 'cloud', desc: 'IaaS vs PaaS vs SaaS, public/private/hybrid cloud, shared responsibility model, and cloud economics.' },
    { id: 2, title: 'Linux & Networking', icon: 'lan', desc: 'VPCs, subnets, routing tables, security groups, NAT gateways, and load balancers.' },
    { id: 3, title: 'Core AWS / GCP / Azure', icon: 'dns', desc: 'Compute (EC2/GCE/VMs), storage (S3/GCS/Blob), databases (RDS/Cloud SQL), and IAM.' },
    { id: 4, title: 'Containers & Docker', icon: 'inventory_2', desc: 'Docker images, containers, volumes, networking, Docker Compose, and container registries.' },
    { id: 5, title: 'Kubernetes', icon: 'settings_suggest', desc: 'Pods, deployments, services, ingress, ConfigMaps, Secrets, Helm charts, and cluster management.' },
    { id: 6, title: 'Infrastructure as Code', icon: 'code', desc: 'Terraform, AWS CloudFormation, Pulumi — declarative infrastructure, state management, and modules.' },
    { id: 7, title: 'CI/CD Pipelines', icon: 'merge', desc: 'GitHub Actions, Jenkins, GitLab CI — automated testing, building, and deployment workflows.' },
    { id: 8, title: 'Serverless', icon: 'bolt', desc: 'AWS Lambda, Cloud Functions, API Gateway, event-driven architecture, and cold start optimization.' },
    { id: 9, title: 'Monitoring & Observability', icon: 'monitor_heart', desc: 'CloudWatch, Prometheus, Grafana, distributed tracing (Jaeger), logging (ELK stack), and alerting.' },
    { id: 10, title: 'Cloud Certifications', icon: 'workspace_premium', desc: 'AWS Solutions Architect, GCP Associate Cloud Engineer, Azure AZ-900/AZ-104, and CKA for Kubernetes.' },
  ],
  robotics: [
    { id: 1, title: 'Math & Physics', icon: 'calculate', desc: 'Linear algebra, calculus, rigid body dynamics, kinematics, and control theory fundamentals.' },
    { id: 2, title: 'Programming for Robotics', icon: 'code', desc: 'C++ and Python for robotics. Real-time constraints, memory management, and embedded systems basics.' },
    { id: 3, title: 'Electronics & Microcontrollers', icon: 'memory', desc: 'Arduino, Raspberry Pi, GPIO, PWM, I2C/SPI/UART protocols, sensors, and actuators.' },
    { id: 4, title: 'ROS (Robot Operating System)', icon: 'precision_manufacturing', desc: 'ROS2 nodes, topics, services, actions, TF transforms, URDF models, and Gazebo simulation.' },
    { id: 5, title: 'Kinematics & Dynamics', icon: 'rotate_90_degrees_cw', desc: 'Forward/inverse kinematics, Denavit-Hartenberg parameters, Jacobians, and trajectory planning.' },
    { id: 6, title: 'Sensors & Perception', icon: 'sensors', desc: 'LiDAR, cameras, IMUs, ultrasonic sensors, sensor fusion (Kalman filter), and point cloud processing.' },
    { id: 7, title: 'Computer Vision for Robotics', icon: 'visibility', desc: 'OpenCV, object detection, pose estimation, depth cameras (RealSense), and visual SLAM.' },
    { id: 8, title: 'Path Planning & Navigation', icon: 'map', desc: 'A*, Dijkstra, RRT, potential fields, SLAM (GMapping, Cartographer), and Nav2 stack.' },
    { id: 9, title: 'Machine Learning in Robotics', icon: 'smart_toy', desc: 'Reinforcement learning (PPO, SAC), imitation learning, sim-to-real transfer, and manipulation.' },
    { id: 10, title: 'Capstone Robot Project', icon: 'star', desc: 'Build an autonomous robot: perception → planning → control loop. Document and present your system.' },
  ],
  devops: [
    { id: 1, title: 'Linux & Shell Scripting', icon: 'terminal', desc: 'File system, permissions, cron jobs, bash scripting, process management, and system monitoring.' },
    { id: 2, title: 'Version Control & Git', icon: 'merge', desc: 'Branching strategies (GitFlow, trunk-based), hooks, monorepos, and code review workflows.' },
    { id: 3, title: 'Networking Basics', icon: 'lan', desc: 'DNS, HTTP/S, TCP/IP, load balancers, reverse proxies (Nginx), and SSL/TLS certificates.' },
    { id: 4, title: 'Docker & Containers', icon: 'inventory_2', desc: 'Dockerfile best practices, multi-stage builds, container networking, volumes, and security scanning.' },
    { id: 5, title: 'Kubernetes', icon: 'settings_suggest', desc: 'Cluster architecture, workloads, networking (CNI), storage (CSI), RBAC, and production hardening.' },
    { id: 6, title: 'CI/CD', icon: 'autorenew', desc: 'GitHub Actions, Jenkins, ArgoCD, GitOps principles, blue-green deployments, and canary releases.' },
    { id: 7, title: 'Infrastructure as Code', icon: 'code', desc: 'Terraform, Ansible, Pulumi — provisioning, configuration management, and drift detection.' },
    { id: 8, title: 'Cloud Platforms', icon: 'cloud', desc: 'AWS/GCP/Azure core services, managed Kubernetes (EKS/GKE/AKS), and cost optimization.' },
    { id: 9, title: 'Monitoring & SRE', icon: 'monitor_heart', desc: 'SLIs/SLOs/SLAs, Prometheus + Grafana, ELK stack, incident management, and chaos engineering.' },
    { id: 10, title: 'Security (DevSecOps)', icon: 'security', desc: 'SAST/DAST in pipelines, secrets management (Vault), container scanning, and compliance as code.' },
  ],
  mobile: [
    { id: 1, title: 'Programming Fundamentals', icon: 'code', desc: 'Dart (Flutter) or Kotlin/Swift. OOP, null safety, async programming, and functional patterns.' },
    { id: 2, title: 'UI Basics', icon: 'phone_android', desc: 'Widgets/Views, layouts, navigation, theming, responsive design, and platform design guidelines (Material/HIG).' },
    { id: 3, title: 'State Management', icon: 'sync', desc: 'Flutter: Riverpod, Bloc, Provider. React Native: Redux, Zustand. Reactive programming patterns.' },
    { id: 4, title: 'Networking & APIs', icon: 'wifi', desc: 'REST API integration, JSON parsing, Dio/Retrofit, error handling, caching, and offline support.' },
    { id: 5, title: 'Local Storage', icon: 'storage', desc: 'SQLite, Hive, SharedPreferences, Room (Android), CoreData (iOS), and secure storage.' },
    { id: 6, title: 'Authentication', icon: 'lock', desc: 'Firebase Auth, OAuth, biometric auth, token refresh flows, and secure credential storage.' },
    { id: 7, title: 'Native Features', icon: 'sensors', desc: 'Camera, GPS, push notifications (FCM/APNs), background tasks, and platform channels.' },
    { id: 8, title: 'Testing', icon: 'bug_report', desc: 'Unit tests, widget tests, integration tests, mocking, and UI automation (Appium, Detox).' },
    { id: 9, title: 'Performance & Optimization', icon: 'speed', desc: 'Rendering performance, memory leaks, lazy loading, image optimization, and profiling tools.' },
    { id: 10, title: 'Publishing & CI/CD', icon: 'publish', desc: 'App signing, Play Store / App Store submission, Fastlane, Codemagic, and crash reporting (Sentry).' },
  ],
}
